### PR TITLE
Chibukasia associated resources

### PR DESCRIPTION
**Pull request by chibukasia**
Please review the code and let me know the changes to be made
NOTE: I have not used update and create with exclamation marks since we have no validations at the moment. I have as well not done the migrations since I need some approval before I migrate

### CODE REVIEW

**Comment by munenebrian** [comment]
i have reviewed the code, it looks great!

**Review by munenebrian — COMMENTED** [review]
I have reviewed the code changes @chibukasia :+1:

**Comment by Katiechi** [comment]
I have reviewed the code, I believe it is fine

**Comment by Tkamunya1** [comment]
Looks okay

**Review by Katiechi — APPROVED** [review]

**Review by Tkamunya1 — APPROVED** [review]

**Pull request merged**
